version: '3.9'
services:

  bookline:
    #build: .
    image: lalyos/bookline
    ports:
      - 8888
    labels:
      - "traefik.frontend.rule=Host:book.${DOMAIN:-lvh.me}"
  
  traefik:
    image: traefik:1.7-alpine
    restart: always
    command:
      - --retry
      #- --debug
      - --rest
      - --docker.domain=${DOMAIN:-lvh.me}
      - --docker.network=traefik
      - --api.dashboard
    labels:
      - "traefik.frontend.rule=Host:traefik.${DOMAIN:-lvh.me}"
      - "traefik.port=8080"
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  prometheus:
    image: prom/prometheus:v2.12.0
    volumes:
        - ./config/prometheus/:/etc/prometheus/
    command:
        - '--config.file=/etc/prometheus/prometheus.yaml'
        - '--storage.tsdb.path=/prometheus'
        - '--storage.tsdb.retention=200h'
        - '--web.enable-lifecycle'
        - '--web.external-url=http://prom.${DOMAIN:-lvh.me}'
    ports:
      - 9090
    labels:
    - "traefik.frontend.rule=Host:prom.${DOMAIN:-lvh.me}"
    - "traefik.port=9090"

  grafana:
    image: grafana/grafana:6.3.3
    ports:
      - 3000
    environment:
        GF_USERS_ALLOW_SIGN_UP: "false"
        GF_AUTH_ANONYMOUS_ENABLED: "true"
        GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    volumes:
        - ./config/grafana:/etc/grafana/provisioning/datasources
    labels:
    - "traefik.frontend.rule=Host:graf.${DOMAIN:-lvh.me}"
    - "traefik.port=3000"